services:
  - type: web
    name: seclog-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 web/app.py
    envVars:
      - key: PORT
        value: 10000
    plan: free
